@extends('template')
@section ('title', 'telefonos')
@section('class','telefonos')

@section ('content')
<div class="container">
	<div class="col-lg-12">
		<h1>BREVE RESEÑA HISTÓRICA DE MOQUEGUA</h1>
		<br>
		<p>
			La región en que se asienta Moquegua era ya conocida y poblada desde antes de la llegada de los incas, hace unos 12000 años. Grupos de cazadores dispersos en la región costera y alto andina conformaron este primer grupo migrante. Con la aparición de la agricultura surgen los huaracanes, grupo alfarero que se asentó alrededor del año 1000 a. C. Alrededor del 500 d.C. llegaron dos grandes civilizaciones: Tiwanaku, de origen altiplánico y, Wari, de Ayacucho, extendiendo sus dominios hasta ocupar el valle de Moquegua y el Cerro Baúl respectivamente. Luego del colapso Tiwanaku-Wari, cobran importancia grupos locales como los chiribayas (950-1350 d.C.) y los estuquiñas o cuchunas (1000-1475 d.C.). Este último integrado al Tahuantinsuyo a la llegada de los incas.
		</p>
		<p>
			No están muy claros los orígenes del asentamiento español en estas tierras cuya fundación posiblemente fue en 1537. Tras varias demandas y querellas entre los poblados españoles de los pueblos de San Sebastián de Escapagua y Santa Catalina de Alejandría, ubicados a ambos lados del río Tambapaya (Moquegua), con dependencias en Arequipa y Chucuito, respectivamente, el XII Virrey del Perú, don Francisco Borja y Aragón, Príncipe de Esquilache, funda sobre el poblado de San Sebastián de Escapagua la Villa de San Francisco de Esquilache, el 27 de marzo de 1618. Los vecinos del pueblo de Santa Catalina, no contentos con la designación de la nueva villa litigaron por su preponderancia ante el XIII Virrey don Diego Fernández de Córdoba, Marqués de Guadalcázar, quien falló a favor de ellos. El Virrey le dio su título, denominándola Villa de Santa Catalina de Guadalcázar del valle de Moquegua, fundándola el 1 de mayo de 1625. Se estableció un cabildo y con una serie de rangos que contribuyeron a dar mayor importancia a la ciudad. La favoreció con toda clase de mercedes y seguramente con privilegio de armas, el que debe descansar en los archivos de Indias. El Marqués ordenó su reedificación, convirtiéndola en uno de los centros de la más rancia aristocracia colonial, edificándose en ella hermosos solares y magníficos templos. 
			Moquegua tuvo una relevante participación de la historia nacional durante el virreinato, destacado y sacrificado papel durante la lucha por defender nuestra soberanía, primeramente, contra el ejército español (1823, batallas de Torata y Moquegua) y luego contra el ejército chileno (1880, batalla de los Ángeles).
			Moquegua se distinguió en la lucha por la independencia. Don Juan Vélez de Córdoba, ejecutado en Oruro en 1737 por su Manifiesto y levantamiento contra el yugo español. Merecen mención don José Manuel Ubalde, don José Gavino, don Pedro Barrios y don Juan Rospigliosi, entre muchos moqueguanos que se sumaron progresivamente a la causa independentista. Esto produjo que, tras el levantamiento de Pumacahua, Moquegua proclamó espontáneamente su independencia en 1814, posiblemente un 9 de noviembre; fue la primera ciudad en el suelo patrio en proclamar independientemente su independencia. Posterior a esta fecha, Moquegua proclamó su independencia en 1823 y 1825.
			La riqueza y economía de la ciudad se sustentaron en su industria vitivinícola, llegando a exportar sus vinos y piscos a Europa, Centro y Sudamérica (Bolivia, Argentina y Chile). A mediados del siglo XIX fue la segunda ciudad en dar mayores ingresos al estado peruano. Luego del sismo de 1868 se construye el ferrocarril (1872), construyéndose además la línea telegráfica. El ferrocarril, así como la pujante industria vitivinícola colapsó tras la Guerra del Pacífico y la plaga de la filoxera, que destruyó los antiquísimos viñedos. Los terremotos han sido los azotes de la Región, que en repetidas ocasiones la dejó en escombros. 
			Durante la Guerra del Pacífico, sus hijos dieron muestras de valor en defensa del suelo patrio. Moquegua fue ocupada y saqueada hasta en cuatro oportunidades por el invasor. Se impuso fuerte cupo de guerra y se cometieron robos, saqueos, atropellos y desmanes en los solares, iglesias y haciendas, quedando estas últimas reducidas a cenizas y destruido las tinajas con productos que no pudieron llevarse; el ferrocarril, el muelle fiscal, las líneas telegráficas en Ilo corrieron una suerte similar. El 22 de marzo de 1880 se suscita la batalla de Los Ángeles. El coronel moqueguano don Julio César Chocano quedó al mando de los destacamentos Granaderos del Cuzco de 300 hombres y la de Gendarmes de Moquegua con 50 hombres, a estos se unió un grupo de distinguidos jóvenes de Moquegua quienes formaron la columna Huáscar, a la que las damas moqueguanas obsequiaron un estandarte bordado (se encuentra en exposición la Sociedad de Artesanos). El ejército peruano compuesto es derrotado y la ciudad es ocupada y afrentada.
			Un paseo por el centro histórico de Moquegua es como remontarse al pasado. Las estrechas calles, sus techos en mojinete, sus plazas, iglesia y conventos, la arquitectura colonial y republicana - civil y religiosa, nos hablan de su esplendoroso pasado y singular arquitectura.
			En la plaza de armas destaca la fuente Eiffel, diseñada por el famoso arquitecto francés; es una de las valiosas joyas que tiene la ciudad. Fue adquirida por los ricos hacendados en 1877 y para su inauguración no se encontró mejor tributo que dejar correr por sus tuberías cientos de litros de vino para el deleite y el jolgorio moqueguano.
			Circundan la plaza sobrias casas solariegas y la fachada de lo que fue la catedral de la antigua villa, La Matriz. La Iglesia Matriz, según narran los historiadores, fue una de las más bellas de la costa sur peruana. En el interior de La Matriz se ubica la Municipalidad y el Museo Contisuyo en donde podemos observar restos arqueológicos que datan de los 12000 años a.C. hasta el período Inca. Restos de tejidos, cerámica, fardos funerarios y piezas de oro y plata correspondientes a las diversas culturas que se asentaron en estos valles.
			Hoy el templo más notable es Santo Domingo, no sólo porque es la mejor expresión del arte religioso de la región, sino porque en el altar se encuentra el cuerpo de Santa Fortunata, virgen y mártir del cristianismo, quien fuera traída de Roma. En el Perú es la única iglesia fuera de Lima que conserva el cuerpo de un santo y una de las pocas que tiene este privilegio en el mundo. Contó Moquegua con uno de los hospitales más antiguos, fundado en 1726, con el nombre de San Juan de Dios. 
			Moquegua es la tierra del sol eterno. En su lenguaje, costumbres, arquitectura y tradiciones se devela su marcada supervivencia hispana. Calles estrechas, rejas sevillanas, balcones de cajón y hermosas casas solariegas, parecen invitar, a propios y extraños, al deleite plácido de sus años mozos, donde la prosperidad y la riqueza convirtieron a esta ciudad en un emporio de cultura y tradición, cuyos viñedos y olivares fueron muy cotizados en América y Europa por su alta calidad. Los corredores y salones nos hablan aún de su glorioso pasado. 
		</p>
	</div>		
	
</div>
@endsection